export const SHOW_CHATBOT = 'SHOW_CHATBOT';
export const HIDE_CHATBOT = 'HIDE_CHATBOT';
export const MOBILE_VIEW_ENABLED ='MOBILE_VIEW_ENABLED'
export const MOBILE_VIEW_DISABLED ='MOBILE_VIEW_DISABLED'
export const SHOW_CERTIFICATIONS = 'SHOW_CERTIFICATIONS'
export const HIDE_CERTIFICATIONS = 'HIDE_CERTIFICATIONS'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR'